# Generated by Django 5.0.6 on 2024-06-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MadiraBackend", "0003_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
