# Generated by Django 5.0.6 on 2024-06-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MadiraBackend", "0004_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
